import os
import sys
import json
import base64
from github import Github, Auth
import google.generativeai as genai

# Configuration
GEMINI_MODEL = "gemini-1.5-pro-latest" # Use Pro for deep reasoning
ISSUE_NUMBER = int(os.getenv("ISSUE_NUMBER"))
REPO_NAME = os.getenv("REPO_NAME")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

def main():
    if not GEMINI_API_KEY:
        print("Error: GEMINI_API_KEY not set")
        sys.exit(1)

    # 1. Initialize Clients
    auth = Auth.Token(GITHUB_TOKEN)
    g = Github(auth=auth)
    repo = g.get_repo(REPO_NAME)
    issue = repo.get_issue(number=ISSUE_NUMBER)
    genai.configure(api_key=GEMINI_API_KEY)
    model = genai.GenerativeModel(GEMINI_MODEL)

    print(f"Analyzing Issue #{ISSUE_NUMBER}: {issue.title}")

    # 2. Gather Context
    # We'll gather the file structure and the content of major files
    file_structure = []
    important_files = {}
    
    for root, dirs, files in os.walk("."):
        if ".git" in root or "venv" in root or "node_modules" in root or "__pycache__" in root:
            continue
        for file in files:
            path = os.path.join(root, file).replace("./", "")
            file_structure.append(path)
            # Only read text files that are likely relevant
            if file.endswith((".py", ".jsx", ".css", ".html", ".js", ".md", ".sh")):
                try:
                    with open(path, "r") as f:
                        important_files[path] = f.read()
                except:
                    pass

    context_str = "FILE STRUCTURE:\n" + "\n".join(file_structure) + "\n\n"
    context_str += "FILE CONTENTS:\n"
    for path, content in important_files.items():
        context_str += f"--- FILE: {path} ---\n{content}\n\n"

    # 3. Prompt Gemini
    prompt = f"""
You are an expert AI software engineer for the OpenSoak project.
An issue has been reported:

TITLE: {issue.title}
DESCRIPTION: {issue.body}

YOUR TASK:
1. Analyze the codebase provided below.
2. Determine which files need to be changed to fix the issue.
3. Provide the NEW COMPLETE CONTENT for each modified file.

CONSTRAINTS:
- Do not make unnecessary changes.
- Adhere to the existing code style.
- Only provide files that need changes.

RESPONSE FORMAT:
Your response must be a valid JSON object with the following structure:
{{
  "explanation": "Briefly explain what was wrong and how you fixed it.",
  "files": [
    {{
      "path": "path/to/file.py",
      "content": "Full new content of the file..."
    }}
  ]
}}

DO NOT provide any text outside the JSON block.

CODEBASE CONTEXT:
{context_str}
"""

    response = model.generate_content(prompt)
    
    # 4. Parse Response
    try:
        # Clean up possible markdown code blocks from response
        clean_json = response.text.strip()
        if clean_json.startswith("```json"):
            clean_json = clean_json[7:-3].strip()
        elif clean_json.startswith("```"):
            clean_json = clean_json[3:-3].strip()
            
        data = json.loads(clean_json)
    except Exception as e:
        print(f"Failed to parse AI response as JSON: {e}")
        print(f"RAW RESPONSE: {response.text}")
        sys.exit(1)

    # 5. Apply Changes and Create PR
    branch_name = f"ai-fix-issue-{ISSUE_NUMBER}"
    base_branch = repo.default_branch
    
    # Create new branch
    sb = repo.get_branch(base_branch)
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=sb.commit.sha)

    # Update files in the new branch
    for file_data in data["files"]:
        path = file_data["path"]
        content = file_data["content"]
        
        try:
            # Check if file exists to get its SHA
            contents = repo.get_contents(path, ref=branch_name)
            repo.update_file(path, f"AI Fix: {issue.title}", content, contents.sha, branch=branch_name)
            print(f"Updated {path}")
        except:
            # Create new file if it doesn't exist
            repo.create_file(path, f"AI Fix: {issue.title}", content, branch=branch_name)
            print(f"Created {path}")

    # 6. Create Pull Request
    pr_body = f"""
## AI-Generated Fix for Issue #{ISSUE_NUMBER}

**Explanation:**
{data['explanation']}

---
*Generated by the OpenSoak AI Fixer Agent.*
"""
    pr = repo.create_pull(
        title=f"AI Fix: {issue.title}",
        body=pr_body,
        head=branch_name,
        base=base_branch
    )

    # 7. Comment on Issue
    issue.create_comment(f"AI Agent has proposed a fix in Pull Request #{pr.number}")
    print(f"PR Created: {pr.html_url}")

if __name__ == "__main__":
    main()
